[build]
  publish = "dist/public"
  command = "npm install && cd netlify/functions && npm install && cd ../.. && vite build && cp _redirects dist/public/_redirects"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/candidates/search"
  to = "/.netlify/functions/candidates-search"
  status = 200

[[redirects]]
  from = "/api/candidates/bulk-import"
  to = "/.netlify/functions/candidates"
  status = 200

[[redirects]]
  from = "/api/candidates/*"
  to = "/.netlify/functions/candidates"
  status = 200

[[redirects]]
  from = "/api/candidates"
  to = "/.netlify/functions/candidates"
  status = 200

[[redirects]]
  from = "/api/send-otp"
  to = "/.netlify/functions/send-otp"
  status = 200

[[redirects]]
  from = "/api/verify-otp"
  to = "/.netlify/functions/verify-otp"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200