[build]
  publish = "dist/public"
  command = "cd netlify/functions && npm install && cd ../.. && vite build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Function redirects in netlify.toml
[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/api/candidates/search"
  to = "/.netlify/functions/candidates-search"
  status = 200

[[redirects]]
  from = "/api/candidates/bulk-import"
  to = "/.netlify/functions/candidates"
  status = 200

[[redirects]]
  from = "/api/candidates/*"
  to = "/.netlify/functions/candidates"
  status = 200
  
[[redirects]]
  from = "/api/candidates"
  to = "/.netlify/functions/candidates"
  status = 200

[[redirects]]
  from = "/api/send-otp"
  to = "/.netlify/functions/send-otp"
  status = 200

[[redirects]]
  from = "/api/verify-otp"
  to = "/.netlify/functions/verify-otp"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200